name: mozilla-django-oidc codecov
on: [pull_request]

jobs:
  codecov:
    runs-on: ubuntu-latest
    name: Codecov
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install codecov tox tox-gh-actions
      - name: Run tox
        run: tox
      - uses: codecov/codecov-action@v1
        with:
          verbose: true
